@startuml trunk
left to right direction
skinparam state {
    BackgroundColor Peru
    BorderColor Black
    FontName Impact
}

actor admin
actor Employee
actor Management
rectangle "Usecase Diagram "{
    admin--(เข้าสู่ระบบ)
    admin--(จัดการข้อมูลพนักงาน)
    Management--(เข้าสู่ระบบ)
    (เข้าสู่ระบบ)--Employee
    (จัดการข้อมูลเช่าลูกค้า)--Employee
    (จัดการคำสั่งเช่ารถบรรทุก)--Employee
    (จัดทำใบเสนอราคา)--Employee
    Management--(อนุมัติใบเสนอราคา)
    (พิมพ์ใบเสร็จ)--Employee
}

@enduml
